BEGIN;

CREATE TABLE IF NOT EXISTS app(
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(300) UNIQUE NOT NULL,
  operating_system_id INTEGER REFERENCES operating_system(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  modified_at TIMESTAMP WITH TIME ZONE NOT NULL
);

COMMIT;
