BEGIN;

CREATE TABLE IF NOT EXISTS phone(
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(300) UNIQUE NOT NULL,
  make_id INTEGER REFERENCES make(id) NOT NULL,
  os_id INTEGER REFERENCES os(id) NOT NULL,
  created_at TIME WITH TIME ZONE NOT NULL,
  modified_at TIME WITH TIME ZONE NOT NULL
);

COMMIT;
