// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package os

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OSWriterClient is the client API for OSWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OSWriterClient interface {
	CreateOne(ctx context.Context, in *CreateOneRequest, opts ...grpc.CallOption) (*CreateOneResponse, error)
}

type oSWriterClient struct {
	cc grpc.ClientConnInterface
}

func NewOSWriterClient(cc grpc.ClientConnInterface) OSWriterClient {
	return &oSWriterClient{cc}
}

func (c *oSWriterClient) CreateOne(ctx context.Context, in *CreateOneRequest, opts ...grpc.CallOption) (*CreateOneResponse, error) {
	out := new(CreateOneResponse)
	err := c.cc.Invoke(ctx, "/os.OSWriter/CreateOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OSWriterServer is the server API for OSWriter service.
// All implementations must embed UnimplementedOSWriterServer
// for forward compatibility
type OSWriterServer interface {
	CreateOne(context.Context, *CreateOneRequest) (*CreateOneResponse, error)
	mustEmbedUnimplementedOSWriterServer()
}

// UnimplementedOSWriterServer must be embedded to have forward compatible implementations.
type UnimplementedOSWriterServer struct {
}

func (UnimplementedOSWriterServer) CreateOne(context.Context, *CreateOneRequest) (*CreateOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOne not implemented")
}
func (UnimplementedOSWriterServer) mustEmbedUnimplementedOSWriterServer() {}

// UnsafeOSWriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OSWriterServer will
// result in compilation errors.
type UnsafeOSWriterServer interface {
	mustEmbedUnimplementedOSWriterServer()
}

func RegisterOSWriterServer(s grpc.ServiceRegistrar, srv OSWriterServer) {
	s.RegisterService(&OSWriter_ServiceDesc, srv)
}

func _OSWriter_CreateOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSWriterServer).CreateOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/os.OSWriter/CreateOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSWriterServer).CreateOne(ctx, req.(*CreateOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OSWriter_ServiceDesc is the grpc.ServiceDesc for OSWriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OSWriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "os.OSWriter",
	HandlerType: (*OSWriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOne",
			Handler:    _OSWriter_CreateOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/os/os_writer.proto",
}
