// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package operating_system

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OperatingSystemWriterClient is the client API for OperatingSystemWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperatingSystemWriterClient interface {
	CreateOne(ctx context.Context, in *CreateOneRequest, opts ...grpc.CallOption) (*CreateOneResponse, error)
}

type operatingSystemWriterClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatingSystemWriterClient(cc grpc.ClientConnInterface) OperatingSystemWriterClient {
	return &operatingSystemWriterClient{cc}
}

func (c *operatingSystemWriterClient) CreateOne(ctx context.Context, in *CreateOneRequest, opts ...grpc.CallOption) (*CreateOneResponse, error) {
	out := new(CreateOneResponse)
	err := c.cc.Invoke(ctx, "/operating_system.OperatingSystemWriter/CreateOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatingSystemWriterServer is the server API for OperatingSystemWriter service.
// All implementations must embed UnimplementedOperatingSystemWriterServer
// for forward compatibility
type OperatingSystemWriterServer interface {
	CreateOne(context.Context, *CreateOneRequest) (*CreateOneResponse, error)
	mustEmbedUnimplementedOperatingSystemWriterServer()
}

// UnimplementedOperatingSystemWriterServer must be embedded to have forward compatible implementations.
type UnimplementedOperatingSystemWriterServer struct {
}

func (UnimplementedOperatingSystemWriterServer) CreateOne(context.Context, *CreateOneRequest) (*CreateOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOne not implemented")
}
func (UnimplementedOperatingSystemWriterServer) mustEmbedUnimplementedOperatingSystemWriterServer() {}

// UnsafeOperatingSystemWriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatingSystemWriterServer will
// result in compilation errors.
type UnsafeOperatingSystemWriterServer interface {
	mustEmbedUnimplementedOperatingSystemWriterServer()
}

func RegisterOperatingSystemWriterServer(s grpc.ServiceRegistrar, srv OperatingSystemWriterServer) {
	s.RegisterService(&OperatingSystemWriter_ServiceDesc, srv)
}

func _OperatingSystemWriter_CreateOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatingSystemWriterServer).CreateOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operating_system.OperatingSystemWriter/CreateOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatingSystemWriterServer).CreateOne(ctx, req.(*CreateOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatingSystemWriter_ServiceDesc is the grpc.ServiceDesc for OperatingSystemWriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatingSystemWriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operating_system.OperatingSystemWriter",
	HandlerType: (*OperatingSystemWriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOne",
			Handler:    _OperatingSystemWriter_CreateOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/operating_system/operating_system_writer.proto",
}
