// Code generated by sqlc. DO NOT EDIT.
// source: os.sql

package os

import (
	"context"
)

const getByID = `-- name: GetByID :one
SELECT id, name, created_at, modified_at FROM os WHERE id = $1 LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id int32) (O, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i O
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
