version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  "Go build":
    docker:
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go build -v ./...
      - run: go test -v ./...
  "Envoy validate config":
    docker:
      - image: "envoyproxy/envoy:v1.15.3@sha256:8e4e3d1c3f291b097a06a1070b4ccad92e870b14c35a76b4d457bc27bf8b7a9a"
    steps:
      - checkout
      - run: make lint-envoy
workflows:
  node-tests:
    jobs:
      - node/test:
          name: "Node.js build"
          app-dir: web
          pkg-manager: yarn
          run-command: build
          version: "15.4.0"
      - node/test:
          name: "Node.js tests"
          app-dir: web
          pkg-manager: yarn
          version: "15.4.0"

  go:
    jobs:
      - "Go build"

  envoy:
    jobs:
      - "Envoy validate config"
