version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  "Go build":
    docker:
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go build -v ./...
      - run: go test -v ./...
workflows:
  node-tests:
    jobs:
      - node/test:
          name: "Node.js build"
          app-dir: web
          pkg-manager: yarn
          run-command: build
      - node/test:
          name: "Node.js tests"
          app-dir: web
          pkg-manager: yarn

  go:
    jobs:
      - "Go build"
