version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  "Bazel build":
    docker:
      - image: gcr.io/cloud-builders/bazel@sha256:15219ed8ff15d72d3615d7c8443a19ce8272947ff75e58253a3d76ef38e48a4c
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - web-template-bazel-v0-{{ checksum ".bazelversion" }}-{{ checksum "WORKSPACE" }}-{{ checksum "api/go.sum" }}
            - web-template-bazel-v0-{{ checksum ".bazelversion" }}-{{ checksum "WORKSPACE" }}
            - web-template-bazel-v0-{{ checksum ".bazelversion" }}
      - restore_cache:
          keys:
            - web-template-bazel-repo-v0-{{ checksum ".bazelversion" }}-{{ checksum "WORKSPACE" }}-{{ checksum "api/go.sum" }}
            - web-template-bazel-repo-v0-{{ checksum ".bazelversion" }}-{{ checksum "WORKSPACE" }}
            - web-template-bazel-repo-v0-{{ checksum ".bazelversion" }}
      - run:
          command: mkdir -p ~/.bazel_cache
      - run:
          command: bazel fetch //... --repository_cache=~/.bazel_repo
      - run:
          command: bazel build //... --disk_cache=~/.bazel_cache --repository_cache=~/.bazel_repo --jobs=2
      - save_cache:
          key: web-template-bazel-repo-v0-{{ checksum ".bazelversion" }}-{{ checksum "WORKSPACE" }}-{{ checksum "api/go.sum" }}
          paths:
            - "~/.bazel_repo"
          when: always
      - save_cache:
          key: web-template-bazel-v0-{{ checksum ".bazelversion" }}-{{ checksum "WORKSPACE" }}-{{ checksum "api/go.sum" }}
          paths:
            - "~/.bazel_cache"
            - "~/.cache/bazelisk"
  "Go build":
    docker:
      - image: circleci/golang:1.16rc1 # TODO: change to 1.16 when available
    resource_class: small
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - run: pwd
      - checkout
      - run:
          command: go build -v ./...
          working_directory: ./api
      - run:
          command: go test -v ./...
          working_directory: ./api
  "Envoy validate config":
    docker:
      - image: "envoyproxy/envoy-alpine:v1.17.0@sha256:47ab124a5b4058a33a995a92de7f566104fc33e8af8302efab577231f3a84e51"
    resource_class: small
    steps:
      - checkout
      - run: envoy --config-path envoy/envoy.yaml --mode validate
workflows:
  bazel:
    jobs:
      - "Bazel build"
  node-tests:
    jobs:
      - node/test:
          name: "Node.js build"
          app-dir: web
          pkg-manager: yarn
          run-command: build
          version: "15.4.0"
      - node/test:
          name: "Node.js tests"
          app-dir: web
          pkg-manager: yarn
          version: "15.4.0"

  go:
    jobs:
      - "Go build"

  envoy:
    jobs:
      - "Envoy validate config"
