version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  "Go build":
    docker:
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - run: pwd
      - checkout
      - run:
          command: go build -v ./...
          working_directory: ./api
      - run:
          command: go test -v ./...
          working_directory: ./api
  "Envoy validate config":
    docker:
      - image: "envoyproxy/envoy-alpine:v1.15.3@sha256:429550bacdf49175a076bb063b1314b317ef2666e08424b2d39088432e229a6b"
    steps:
      - checkout
      - run: envoy --config-path envoy/envoy.yaml --mode validate
workflows:
  node-tests:
    jobs:
      - node/test:
          name: "Node.js build"
          app-dir: web
          pkg-manager: yarn
          run-command: build
          version: "15.4.0"
      - node/test:
          name: "Node.js tests"
          app-dir: web
          pkg-manager: yarn
          version: "15.4.0"

  go:
    jobs:
      - "Go build"

  envoy:
    jobs:
      - "Envoy validate config"
