// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rickypai/web-template/api/ent/manufacturer"
	"github.com/rickypai/web-template/api/ent/os"
	"github.com/rickypai/web-template/api/ent/predicate"
)

// OSUpdate is the builder for updating OS entities.
type OSUpdate struct {
	config
	hooks    []Hook
	mutation *OSMutation
}

// Where adds a new predicate for the OSUpdate builder.
func (ou *OSUpdate) Where(ps ...predicate.OS) *OSUpdate {
	ou.mutation.predicates = append(ou.mutation.predicates, ps...)
	return ou
}

// SetName sets the "name" field.
func (ou *OSUpdate) SetName(s string) *OSUpdate {
	ou.mutation.SetName(s)
	return ou
}

// SetModifiedAt sets the "modified_at" field.
func (ou *OSUpdate) SetModifiedAt(t time.Time) *OSUpdate {
	ou.mutation.SetModifiedAt(t)
	return ou
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (ou *OSUpdate) SetNillableModifiedAt(t *time.Time) *OSUpdate {
	if t != nil {
		ou.SetModifiedAt(*t)
	}
	return ou
}

// SetPhonesID sets the "phones" edge to the Manufacturer entity by ID.
func (ou *OSUpdate) SetPhonesID(id int) *OSUpdate {
	ou.mutation.SetPhonesID(id)
	return ou
}

// SetNillablePhonesID sets the "phones" edge to the Manufacturer entity by ID if the given value is not nil.
func (ou *OSUpdate) SetNillablePhonesID(id *int) *OSUpdate {
	if id != nil {
		ou = ou.SetPhonesID(*id)
	}
	return ou
}

// SetPhones sets the "phones" edge to the Manufacturer entity.
func (ou *OSUpdate) SetPhones(m *Manufacturer) *OSUpdate {
	return ou.SetPhonesID(m.ID)
}

// Mutation returns the OSMutation object of the builder.
func (ou *OSUpdate) Mutation() *OSMutation {
	return ou.mutation
}

// ClearPhones clears the "phones" edge to the Manufacturer entity.
func (ou *OSUpdate) ClearPhones() *OSUpdate {
	ou.mutation.ClearPhones()
	return ou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OSUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ou.hooks) == 0 {
		if err = ou.check(); err != nil {
			return 0, err
		}
		affected, err = ou.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OSMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ou.check(); err != nil {
				return 0, err
			}
			ou.mutation = mutation
			affected, err = ou.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ou.hooks) - 1; i >= 0; i-- {
			mut = ou.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ou.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OSUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OSUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OSUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OSUpdate) check() error {
	if v, ok := ou.mutation.Name(); ok {
		if err := os.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	return nil
}

func (ou *OSUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   os.Table,
			Columns: os.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: os.FieldID,
			},
		},
	}
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: os.FieldName,
		})
	}
	if value, ok := ou.mutation.ModifiedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: os.FieldModifiedAt,
		})
	}
	if ou.mutation.PhonesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   os.PhonesTable,
			Columns: []string{os.PhonesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manufacturer.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.PhonesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   os.PhonesTable,
			Columns: []string{os.PhonesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manufacturer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{os.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// OSUpdateOne is the builder for updating a single OS entity.
type OSUpdateOne struct {
	config
	hooks    []Hook
	mutation *OSMutation
}

// SetName sets the "name" field.
func (ouo *OSUpdateOne) SetName(s string) *OSUpdateOne {
	ouo.mutation.SetName(s)
	return ouo
}

// SetModifiedAt sets the "modified_at" field.
func (ouo *OSUpdateOne) SetModifiedAt(t time.Time) *OSUpdateOne {
	ouo.mutation.SetModifiedAt(t)
	return ouo
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (ouo *OSUpdateOne) SetNillableModifiedAt(t *time.Time) *OSUpdateOne {
	if t != nil {
		ouo.SetModifiedAt(*t)
	}
	return ouo
}

// SetPhonesID sets the "phones" edge to the Manufacturer entity by ID.
func (ouo *OSUpdateOne) SetPhonesID(id int) *OSUpdateOne {
	ouo.mutation.SetPhonesID(id)
	return ouo
}

// SetNillablePhonesID sets the "phones" edge to the Manufacturer entity by ID if the given value is not nil.
func (ouo *OSUpdateOne) SetNillablePhonesID(id *int) *OSUpdateOne {
	if id != nil {
		ouo = ouo.SetPhonesID(*id)
	}
	return ouo
}

// SetPhones sets the "phones" edge to the Manufacturer entity.
func (ouo *OSUpdateOne) SetPhones(m *Manufacturer) *OSUpdateOne {
	return ouo.SetPhonesID(m.ID)
}

// Mutation returns the OSMutation object of the builder.
func (ouo *OSUpdateOne) Mutation() *OSMutation {
	return ouo.mutation
}

// ClearPhones clears the "phones" edge to the Manufacturer entity.
func (ouo *OSUpdateOne) ClearPhones() *OSUpdateOne {
	ouo.mutation.ClearPhones()
	return ouo
}

// Save executes the query and returns the updated OS entity.
func (ouo *OSUpdateOne) Save(ctx context.Context) (*OS, error) {
	var (
		err  error
		node *OS
	)
	if len(ouo.hooks) == 0 {
		if err = ouo.check(); err != nil {
			return nil, err
		}
		node, err = ouo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OSMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ouo.check(); err != nil {
				return nil, err
			}
			ouo.mutation = mutation
			node, err = ouo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ouo.hooks) - 1; i >= 0; i-- {
			mut = ouo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ouo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OSUpdateOne) SaveX(ctx context.Context) *OS {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OSUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OSUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OSUpdateOne) check() error {
	if v, ok := ouo.mutation.Name(); ok {
		if err := os.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	return nil
}

func (ouo *OSUpdateOne) sqlSave(ctx context.Context) (_node *OS, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   os.Table,
			Columns: os.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: os.FieldID,
			},
		},
	}
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing OS.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: os.FieldName,
		})
	}
	if value, ok := ouo.mutation.ModifiedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: os.FieldModifiedAt,
		})
	}
	if ouo.mutation.PhonesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   os.PhonesTable,
			Columns: []string{os.PhonesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manufacturer.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.PhonesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   os.PhonesTable,
			Columns: []string{os.PhonesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manufacturer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OS{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{os.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
