// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rickypai/web-template/api/ent/manufacturer"
	"github.com/rickypai/web-template/api/ent/operatingsystem"
	"github.com/rickypai/web-template/api/ent/phone"
)

// PhoneCreate is the builder for creating a Phone entity.
type PhoneCreate struct {
	config
	mutation *PhoneMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *PhoneCreate) SetName(s string) *PhoneCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *PhoneCreate) SetCreatedAt(t time.Time) *PhoneCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PhoneCreate) SetNillableCreatedAt(t *time.Time) *PhoneCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetModifiedAt sets the "modified_at" field.
func (pc *PhoneCreate) SetModifiedAt(t time.Time) *PhoneCreate {
	pc.mutation.SetModifiedAt(t)
	return pc
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (pc *PhoneCreate) SetNillableModifiedAt(t *time.Time) *PhoneCreate {
	if t != nil {
		pc.SetModifiedAt(*t)
	}
	return pc
}

// SetManufacturerID sets the "manufacturer" edge to the Manufacturer entity by ID.
func (pc *PhoneCreate) SetManufacturerID(id int) *PhoneCreate {
	pc.mutation.SetManufacturerID(id)
	return pc
}

// SetNillableManufacturerID sets the "manufacturer" edge to the Manufacturer entity by ID if the given value is not nil.
func (pc *PhoneCreate) SetNillableManufacturerID(id *int) *PhoneCreate {
	if id != nil {
		pc = pc.SetManufacturerID(*id)
	}
	return pc
}

// SetManufacturer sets the "manufacturer" edge to the Manufacturer entity.
func (pc *PhoneCreate) SetManufacturer(m *Manufacturer) *PhoneCreate {
	return pc.SetManufacturerID(m.ID)
}

// SetOsID sets the "os" edge to the OperatingSystem entity by ID.
func (pc *PhoneCreate) SetOsID(id int) *PhoneCreate {
	pc.mutation.SetOsID(id)
	return pc
}

// SetNillableOsID sets the "os" edge to the OperatingSystem entity by ID if the given value is not nil.
func (pc *PhoneCreate) SetNillableOsID(id *int) *PhoneCreate {
	if id != nil {
		pc = pc.SetOsID(*id)
	}
	return pc
}

// SetOs sets the "os" edge to the OperatingSystem entity.
func (pc *PhoneCreate) SetOs(o *OperatingSystem) *PhoneCreate {
	return pc.SetOsID(o.ID)
}

// Mutation returns the PhoneMutation object of the builder.
func (pc *PhoneCreate) Mutation() *PhoneMutation {
	return pc.mutation
}

// Save creates the Phone in the database.
func (pc *PhoneCreate) Save(ctx context.Context) (*Phone, error) {
	var (
		err  error
		node *Phone
	)
	pc.defaults()
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhoneMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PhoneCreate) SaveX(ctx context.Context) *Phone {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (pc *PhoneCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := phone.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.ModifiedAt(); !ok {
		v := phone.DefaultModifiedAt()
		pc.mutation.SetModifiedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PhoneCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := phone.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New("ent: missing required field \"created_at\"")}
	}
	if _, ok := pc.mutation.ModifiedAt(); !ok {
		return &ValidationError{Name: "modified_at", err: errors.New("ent: missing required field \"modified_at\"")}
	}
	return nil
}

func (pc *PhoneCreate) sqlSave(ctx context.Context) (*Phone, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pc *PhoneCreate) createSpec() (*Phone, *sqlgraph.CreateSpec) {
	var (
		_node = &Phone{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: phone.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: phone.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: phone.FieldName,
		})
		_node.Name = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: phone.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.ModifiedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: phone.FieldModifiedAt,
		})
		_node.ModifiedAt = value
	}
	if nodes := pc.mutation.ManufacturerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   phone.ManufacturerTable,
			Columns: []string{phone.ManufacturerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: manufacturer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.phone_manufacturer = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.OsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   phone.OsTable,
			Columns: []string{phone.OsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: operatingsystem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.phone_os = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PhoneCreateBulk is the builder for creating many Phone entities in bulk.
type PhoneCreateBulk struct {
	config
	builders []*PhoneCreate
}

// Save creates the Phone entities in the database.
func (pcb *PhoneCreateBulk) Save(ctx context.Context) ([]*Phone, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Phone, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PhoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PhoneCreateBulk) SaveX(ctx context.Context) []*Phone {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
