// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/rickypai/web-template/api/ent/manufacturer"
	"github.com/rickypai/web-template/api/ent/os"
	"github.com/rickypai/web-template/api/ent/phone"
	"github.com/rickypai/web-template/api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	manufacturerFields := schema.Manufacturer{}.Fields()
	_ = manufacturerFields
	// manufacturerDescName is the schema descriptor for name field.
	manufacturerDescName := manufacturerFields[0].Descriptor()
	// manufacturer.NameValidator is a validator for the "name" field. It is called by the builders before save.
	manufacturer.NameValidator = manufacturerDescName.Validators[0].(func(string) error)
	// manufacturerDescCreatedAt is the schema descriptor for created_at field.
	manufacturerDescCreatedAt := manufacturerFields[1].Descriptor()
	// manufacturer.DefaultCreatedAt holds the default value on creation for the created_at field.
	manufacturer.DefaultCreatedAt = manufacturerDescCreatedAt.Default.(func() time.Time)
	// manufacturerDescModifiedAt is the schema descriptor for modified_at field.
	manufacturerDescModifiedAt := manufacturerFields[2].Descriptor()
	// manufacturer.DefaultModifiedAt holds the default value on creation for the modified_at field.
	manufacturer.DefaultModifiedAt = manufacturerDescModifiedAt.Default.(func() time.Time)
	osFields := schema.OS{}.Fields()
	_ = osFields
	// osDescName is the schema descriptor for name field.
	osDescName := osFields[0].Descriptor()
	// os.NameValidator is a validator for the "name" field. It is called by the builders before save.
	os.NameValidator = osDescName.Validators[0].(func(string) error)
	// osDescCreatedAt is the schema descriptor for created_at field.
	osDescCreatedAt := osFields[1].Descriptor()
	// os.DefaultCreatedAt holds the default value on creation for the created_at field.
	os.DefaultCreatedAt = osDescCreatedAt.Default.(func() time.Time)
	// osDescModifiedAt is the schema descriptor for modified_at field.
	osDescModifiedAt := osFields[2].Descriptor()
	// os.DefaultModifiedAt holds the default value on creation for the modified_at field.
	os.DefaultModifiedAt = osDescModifiedAt.Default.(func() time.Time)
	phoneFields := schema.Phone{}.Fields()
	_ = phoneFields
	// phoneDescName is the schema descriptor for name field.
	phoneDescName := phoneFields[0].Descriptor()
	// phone.NameValidator is a validator for the "name" field. It is called by the builders before save.
	phone.NameValidator = phoneDescName.Validators[0].(func(string) error)
	// phoneDescCreatedAt is the schema descriptor for created_at field.
	phoneDescCreatedAt := phoneFields[1].Descriptor()
	// phone.DefaultCreatedAt holds the default value on creation for the created_at field.
	phone.DefaultCreatedAt = phoneDescCreatedAt.Default.(func() time.Time)
	// phoneDescModifiedAt is the schema descriptor for modified_at field.
	phoneDescModifiedAt := phoneFields[2].Descriptor()
	// phone.DefaultModifiedAt holds the default value on creation for the modified_at field.
	phone.DefaultModifiedAt = phoneDescModifiedAt.Default.(func() time.Time)
}
