// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/rickypai/web-template/api/ent/manufacturer"
	"github.com/rickypai/web-template/api/ent/operatingsystem"
	"github.com/rickypai/web-template/api/ent/phone"
	"github.com/rickypai/web-template/api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	manufacturerFields := schema.Manufacturer{}.Fields()
	_ = manufacturerFields
	// manufacturerDescName is the schema descriptor for name field.
	manufacturerDescName := manufacturerFields[0].Descriptor()
	// manufacturer.NameValidator is a validator for the "name" field. It is called by the builders before save.
	manufacturer.NameValidator = manufacturerDescName.Validators[0].(func(string) error)
	// manufacturerDescCreatedAt is the schema descriptor for created_at field.
	manufacturerDescCreatedAt := manufacturerFields[1].Descriptor()
	// manufacturer.DefaultCreatedAt holds the default value on creation for the created_at field.
	manufacturer.DefaultCreatedAt = manufacturerDescCreatedAt.Default.(func() time.Time)
	// manufacturerDescModifiedAt is the schema descriptor for modified_at field.
	manufacturerDescModifiedAt := manufacturerFields[2].Descriptor()
	// manufacturer.DefaultModifiedAt holds the default value on creation for the modified_at field.
	manufacturer.DefaultModifiedAt = manufacturerDescModifiedAt.Default.(func() time.Time)
	operatingsystemFields := schema.OperatingSystem{}.Fields()
	_ = operatingsystemFields
	// operatingsystemDescName is the schema descriptor for name field.
	operatingsystemDescName := operatingsystemFields[0].Descriptor()
	// operatingsystem.NameValidator is a validator for the "name" field. It is called by the builders before save.
	operatingsystem.NameValidator = operatingsystemDescName.Validators[0].(func(string) error)
	// operatingsystemDescCreatedAt is the schema descriptor for created_at field.
	operatingsystemDescCreatedAt := operatingsystemFields[1].Descriptor()
	// operatingsystem.DefaultCreatedAt holds the default value on creation for the created_at field.
	operatingsystem.DefaultCreatedAt = operatingsystemDescCreatedAt.Default.(func() time.Time)
	// operatingsystemDescModifiedAt is the schema descriptor for modified_at field.
	operatingsystemDescModifiedAt := operatingsystemFields[2].Descriptor()
	// operatingsystem.DefaultModifiedAt holds the default value on creation for the modified_at field.
	operatingsystem.DefaultModifiedAt = operatingsystemDescModifiedAt.Default.(func() time.Time)
	phoneFields := schema.Phone{}.Fields()
	_ = phoneFields
	// phoneDescName is the schema descriptor for name field.
	phoneDescName := phoneFields[0].Descriptor()
	// phone.NameValidator is a validator for the "name" field. It is called by the builders before save.
	phone.NameValidator = phoneDescName.Validators[0].(func(string) error)
	// phoneDescCreatedAt is the schema descriptor for created_at field.
	phoneDescCreatedAt := phoneFields[1].Descriptor()
	// phone.DefaultCreatedAt holds the default value on creation for the created_at field.
	phone.DefaultCreatedAt = phoneDescCreatedAt.Default.(func() time.Time)
	// phoneDescModifiedAt is the schema descriptor for modified_at field.
	phoneDescModifiedAt := phoneFields[2].Descriptor()
	// phone.DefaultModifiedAt holds the default value on creation for the modified_at field.
	phone.DefaultModifiedAt = phoneDescModifiedAt.Default.(func() time.Time)
}
