// Code generated by sqlc. DO NOT EDIT.

package app

import (
	"time"
)

type App struct {
	ID                int64
	Name              string
	OperatingSystemID int32
	CreatedAt         time.Time
	ModifiedAt        time.Time
}
