// Code generated by sqlc. DO NOT EDIT.

package manufacturer

import (
	"context"
)

type Querier interface {
	CountTotal(ctx context.Context) (int64, error)
	CreateOne(ctx context.Context, arg CreateOneParams) (Manufacturer, error)
	GetByID(ctx context.Context, id int64) (Manufacturer, error)
	GetManyByIDs(ctx context.Context, dollar_1 []int64) ([]Manufacturer, error)
	ListByPattern(ctx context.Context, arg ListByPatternParams) ([]Manufacturer, error)
	ListOffset(ctx context.Context, arg ListOffsetParams) ([]Manufacturer, error)
}

var _ Querier = (*Queries)(nil)
