// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package manufacturer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ManufacturerWriterClient is the client API for ManufacturerWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManufacturerWriterClient interface {
	CreateOne(ctx context.Context, in *CreateOneRequest, opts ...grpc.CallOption) (*CreateOneResponse, error)
}

type manufacturerWriterClient struct {
	cc grpc.ClientConnInterface
}

func NewManufacturerWriterClient(cc grpc.ClientConnInterface) ManufacturerWriterClient {
	return &manufacturerWriterClient{cc}
}

func (c *manufacturerWriterClient) CreateOne(ctx context.Context, in *CreateOneRequest, opts ...grpc.CallOption) (*CreateOneResponse, error) {
	out := new(CreateOneResponse)
	err := c.cc.Invoke(ctx, "/manufacturer.ManufacturerWriter/CreateOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManufacturerWriterServer is the server API for ManufacturerWriter service.
// All implementations must embed UnimplementedManufacturerWriterServer
// for forward compatibility
type ManufacturerWriterServer interface {
	CreateOne(context.Context, *CreateOneRequest) (*CreateOneResponse, error)
	mustEmbedUnimplementedManufacturerWriterServer()
}

// UnimplementedManufacturerWriterServer must be embedded to have forward compatible implementations.
type UnimplementedManufacturerWriterServer struct {
}

func (UnimplementedManufacturerWriterServer) CreateOne(context.Context, *CreateOneRequest) (*CreateOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOne not implemented")
}
func (UnimplementedManufacturerWriterServer) mustEmbedUnimplementedManufacturerWriterServer() {}

// UnsafeManufacturerWriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManufacturerWriterServer will
// result in compilation errors.
type UnsafeManufacturerWriterServer interface {
	mustEmbedUnimplementedManufacturerWriterServer()
}

func RegisterManufacturerWriterServer(s grpc.ServiceRegistrar, srv ManufacturerWriterServer) {
	s.RegisterService(&ManufacturerWriter_ServiceDesc, srv)
}

func _ManufacturerWriter_CreateOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManufacturerWriterServer).CreateOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manufacturer.ManufacturerWriter/CreateOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManufacturerWriterServer).CreateOne(ctx, req.(*CreateOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManufacturerWriter_ServiceDesc is the grpc.ServiceDesc for ManufacturerWriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManufacturerWriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manufacturer.ManufacturerWriter",
	HandlerType: (*ManufacturerWriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOne",
			Handler:    _ManufacturerWriter_CreateOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/manufacturer/manufacturer_writer.proto",
}
