// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Manufacturer is the predicate function for manufacturer builders.
type Manufacturer func(*sql.Selector)

// OperatingSystem is the predicate function for operatingsystem builders.
type OperatingSystem func(*sql.Selector)

// Phone is the predicate function for phone builders.
type Phone func(*sql.Selector)
