database: web_template_dev
tables:
  - name: manufacturers
    filename_override: manufacturer
  - name: phones
    filename_override: phone
  - name: apps
    filename_override: app
  - name: operating_systems
    filename_override: operating_system
